-- Public site form storage (used by Vercel functions with service role key).

create table if not exists public.contact_enquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  subject text,
  message text not null,
  created_at timestamptz default now()
);

create table if not exists public.admission_enquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text not null,
  course text not null,
  query text not null,
  status text default 'new',
  created_at timestamptz default now()
);

alter table public.contact_enquiries enable row level security;
alter table public.admission_enquiries enable row level security;

-- Public inserts allowed (optional; you can also keep inserts server-only by removing these policies).
drop policy if exists "public insert contact" on public.contact_enquiries;
create policy "public insert contact"
on public.contact_enquiries for insert
to anon
with check (true);

drop policy if exists "public insert admissions" on public.admission_enquiries;
create policy "public insert admissions"
on public.admission_enquiries for insert
to anon
with check (true);

-- Public select denied.
drop policy if exists "deny public select contact" on public.contact_enquiries;
create policy "deny public select contact"
on public.contact_enquiries for select
to anon
using (false);

drop policy if exists "deny public select admissions" on public.admission_enquiries;
create policy "deny public select admissions"
on public.admission_enquiries for select
to anon
using (false);

