-- RRDCH Full Schema — Updated for portal integration
-- Run this in Supabase SQL Editor

-- ─── OPD Queue (public summary) ───────────────────────────────────────
create table if not exists public.opd_queue (
  id                bigint generated by default as identity primary key,
  department        text not null,
  doctor_name       text,
  current_token     text,
  total_waiting     integer default 0,
  est_wait_minutes  integer default 0,
  status            text default 'open',
  updated_at        timestamptz default now()
);

-- ─── OPD Visits / Appointments ────────────────────────────────────────
create table if not exists public.opd_visits (
  id            bigint generated by default as identity primary key,
  token         text,
  department    text not null,
  patient_name  text not null,
  age           integer,
  phone         text,
  reason        text,
  doctor_name   text,
  status        text default 'waiting',
  notes         text,
  scheduled_at  timestamptz default now(),
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

-- ─── Patients ──────────────────────────────────────────────────────────
create table if not exists public.patients (
  id           bigint generated by default as identity primary key,
  name         text not null,
  email        text,
  phone        text,
  age          integer,
  patient_id   text,
  status       text default 'active',
  last_visit   date,
  created_at   timestamptz default now()
);

-- ─── Case Notes ────────────────────────────────────────────────────────
create table if not exists public.case_notes (
  id            bigint generated by default as identity primary key,
  patient_info  text,
  diagnosis     text,
  treatment     text,
  prescription  text,
  notes         text,
  doctor_name   text,
  department    text,
  token_no      text,
  created_at    timestamptz default now()
);

-- ─── Chatbot Sessions ──────────────────────────────────────────────────
create table if not exists public.chatbot_sessions (
  id              bigint generated by default as identity primary key,
  session_id      text,
  query           text,
  response        text,
  mode            text,
  urgency         text default 'Routine',
  department      text,
  user_role       text default 'patient',
  created_at      timestamptz default now()
);

-- ─── Admin Audit Log ───────────────────────────────────────────────────
create table if not exists public.admin_audit_log (
  id           bigint generated by default as identity primary key,
  user_email   text,
  role         text,
  action       text,
  status       text default 'success',
  ip           text,
  created_at   timestamptz default now()
);

-- ─── RLS Policies ─────────────────────────────────────────────────────
alter table public.opd_queue          enable row level security;
alter table public.opd_visits         enable row level security;
alter table public.patients           enable row level security;
alter table public.case_notes         enable row level security;
alter table public.chatbot_sessions   enable row level security;
alter table public.admin_audit_log    enable row level security;

-- Public read for queue summary (patient-facing queue display)
drop policy if exists "public read opd_queue" on public.opd_queue;
create policy "public read opd_queue" on public.opd_queue
  for select to anon using (true);

-- Allow anon inserts for chatbot sessions
drop policy if exists "anon insert chatbot" on public.chatbot_sessions;
create policy "anon insert chatbot" on public.chatbot_sessions
  for insert to anon with check (true);

-- Allow anon inserts for audit log (login events)
drop policy if exists "anon insert audit" on public.admin_audit_log;
create policy "anon insert audit" on public.admin_audit_log
  for insert to anon with check (true);

-- Allow anon inserts for patient registration
drop policy if exists "anon insert patients" on public.patients;
create policy "anon insert patients" on public.patients
  for insert to anon with check (true);

-- Allow anon inserts for appointment booking
drop policy if exists "anon insert visits" on public.opd_visits;
create policy "anon insert visits" on public.opd_visits
  for insert to anon with check (true);

-- Allow anon read of visits (for doctor portal demo)
drop policy if exists "anon read visits" on public.opd_visits;
create policy "anon read visits" on public.opd_visits
  for select to anon using (true);

-- Allow anon update of visit status (queue actions)
drop policy if exists "anon update visits" on public.opd_visits;
create policy "anon update visits" on public.opd_visits
  for update to anon using (true);

-- Allow anon insert for case notes
drop policy if exists "anon insert notes" on public.case_notes;
create policy "anon insert notes" on public.case_notes
  for insert to anon with check (true);

-- Allow anon read of patients
drop policy if exists "anon read patients" on public.patients;
create policy "anon read patients" on public.patients
  for select to anon using (true);

-- Realtime for patient queue and visits
alter publication supabase_realtime add table public.opd_queue;
alter publication supabase_realtime add table public.opd_visits;

-- ─── Seed demo data (opd_visits) ──────────────────────────────────────
insert into public.opd_visits (token, department, patient_name, phone, reason, status, scheduled_at)
values
  ('#001', 'Oral Surgery',           'Ananya Rao',    '9845112233', 'Tooth Extraction',      'done',    now() - interval '3 hours'),
  ('#002', 'Oral Surgery',           'Ravi Kumar',    '9900556677', 'Post-op Checkup',       'ongoing', now() - interval '1 hour'),
  ('#003', 'Orthodontics',           'Meera Sharma',  '9876543210', 'Braces Adjustment',     'waiting', now()),
  ('#004', 'Periodontology',         'Farhan Iqbal',  '9123456789', 'Gum Bleeding',          'waiting', now()),
  ('#005', 'Conservative Dentistry', 'Lakshmi D.',    '9988776655', 'Root Canal Treatment',  'called',  now()),
  ('#006', 'Pedodontics',            'Suresh Nair',   '9765432100', 'Milk Tooth Decay',      'waiting', now() + interval '30 min')
on conflict do nothing;
