-- RRDCH queue schema for secure split access.

create table if not exists public.opd_queue (
  id bigint generated by default as identity primary key,
  department text not null unique,
  doctor_name text,
  current_token text,
  total_waiting integer default 0,
  est_wait_minutes integer default 0,
  status text default 'open',
  updated_at timestamptz default now()
);

create table if not exists public.opd_visits (
  id bigint generated by default as identity primary key,
  token text not null unique,
  department text not null,
  patient_name text not null,
  age integer,
  phone text,
  reason text,
  status text default 'waiting',
  notes text,
  scheduled_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.opd_queue enable row level security;
alter table public.opd_visits enable row level security;

-- Public can read summary queue only.
drop policy if exists "public read opd_queue" on public.opd_queue;
create policy "public read opd_queue"
on public.opd_queue for select
to anon
using (true);

-- Nobody reads/writes detailed visits from anon.
drop policy if exists "deny anon visits select" on public.opd_visits;
create policy "deny anon visits select"
on public.opd_visits for select
to anon
using (false);

-- Realtime source for patient-facing queue.
alter publication supabase_realtime add table public.opd_queue;
